<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppBundleDocumentProyectoHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['nombre']) || (! empty($this->class->fieldMappings['nombre']['nullable']) && array_key_exists('nombre', $data))) {
            $value = $data['nombre'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['nombre']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['nombre']->setValue($document, $return);
            $hydratedData['nombre'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['descripcion']) || (! empty($this->class->fieldMappings['descripcion']['nullable']) && array_key_exists('descripcion', $data))) {
            $value = $data['descripcion'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['descripcion']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['descripcion']->setValue($document, $return);
            $hydratedData['descripcion'] = $return;
        }

        /** @Field(type="float") */
        if (isset($data['precio']) || (! empty($this->class->fieldMappings['precio']['nullable']) && array_key_exists('precio', $data))) {
            $value = $data['precio'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['precio']['type'];
                $return = (float) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['precio']->setValue($document, $return);
            $hydratedData['precio'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['cliente'])) {
            $reference = $data['cliente'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['cliente'], $reference);
            $mongoId = ClassMetadata::getReferenceId($reference, $this->class->fieldMappings['cliente']['storeAs']);
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['cliente']->setValue($document, $return);
            $hydratedData['cliente'] = $return;
        }
        return $hydratedData;
    }
}